font:
  ############################
  ##                        ##
  ##  Material Design Icons ##
  ##                        ##
  ############################
  - file: ${MDI_FONT_DIR}
    id: font_mdi_medium_large
    size: ${MDI_FONT_SIZE_LG}
    glyphs: &mdi-weather-glyphs
      - "\U000F0590" # mdi-weather-cloudy
      - "\U000F0F2F" # mdi-weather-cloudy-alert
      - "\U000F0E6E" # mdi-weather-cloudy-arrow-right
      - "\U000F0591" # mdi-weather-fog
      - "\U000F0592" # mdi-weather-hail
      - "\U000F0F30" # mdi-weather-hazy
      - "\U000F0898" # mdi-weather-hurricane
      - "\U000F0593" # mdi-weather-lightning
      - "\U000F067E" # mdi-weather-lightning-rainy
      - "\U000F0594" # mdi-weather-night
      - "\U000F0F31" # mdi-weather-night-partly-cloudy
      - "\U000F0595" # mdi-weather-partly-cloudy
      - "\U000F0F32" # mdi-weather-partly-lightning
      - "\U000F0F33" # mdi-weather-partly-rainy
      - "\U000F0F34" # mdi-weather-partly-snowy
      - "\U000F0F35" # mdi-weather-partly-snowy-rainy
      - "\U000F0596" # mdi-weather-pouring
      - "\U000F0597" # mdi-weather-rainy
      - "\U000F0598" # mdi-weather-snowy
      - "\U000F0F36" # mdi-weather-snowy-heavy
      - "\U000F067F" # mdi-weather-snowy-rainy
      - "\U000F0599" # mdi-weather-sunny
      - "\U000F0F37" # mdi-weather-sunny-alert
      - "\U000F14E4" # mdi-weather-sunny-off
      - "\U000F059A" # mdi-weather-sunset
      - "\U000F059B" # mdi-weather-sunset-down
      - "\U000F059C" # mdi-weather-sunset-up
      - "\U000F0F38" # mdi-weather-tornado
      - "\U000F059D" # mdi-weather-windy
      - "\U000F059E" # mdi-weather-windy-variant
      - "\U000F00ED" #Calendar
      - "\U000F05A9" #Wifi
      - "\U000F01B4" #Trash
      - "\U000F044C" #Recycle
      - "\U000F010B" #Car

  - file: ${MDI_FONT_DIR}
    id: font_mdi_medium
    size: ${MDI_FONT_SIZE_MED}
    glyphs: *mdi-weather-glyphs

  - file: ${MDI_FONT_DIR}
    id: font_mdi_small
    size: ${MDI_FONT_SIZE_SM}
    glyphs: *mdi-weather-glyphs

  ############################
  ##                        ##
  ##    Google Sans Font    ##
  ##        Regular         ##
  ##                        ##
  ############################
  - file: ${G_SANS_REG_FONT_DIR}
    id: font_google_regular_large
    size: ${G_SANS_REG_SIZE_LG}

  - file: ${G_SANS_REG_FONT_DIR}
    id: font_google_regular_medium
    size: ${G_SANS_REG_SIZE_MED}

  - file: ${G_SANS_REG_FONT_DIR}
    id: font_google_regular_small
    size: ${G_SANS_REG_SIZE_SM}

  ############################
  ##                        ##
  ##    Google Sans Font    ##
  ##          Bold          ##
  ##                        ##
  ############################

  - file: ${G_SANS_BOLD_FONT_DIR}
    id: font_google_bold_x_large
    size: ${G_SANS_BOLD_SIZE_XL}

  - file: ${G_SANS_BOLD_FONT_DIR}
    id: font_google_bold_large
    size: ${G_SANS_BOLD_SIZE_LG}

  - file: ${G_SANS_BOLD_FONT_DIR}
    id: font_google_bold_medium
    size: ${G_SANS_BOLD_SIZE_MED}

  - file: ${G_SANS_BOLD_FONT_DIR}
    id: font_google_bold_small_medium
    size: ${G_SANS_BOLD_SIZE_SM_MED}

  - file: ${G_SANS_BOLD_FONT_DIR}
    id: font_google_bold_small
    size: ${G_SANS_BOLD_SIZE_SM}
