substitutions:
  EVENT_0_ENTITY: sensor.calendar_event_1
  EVENT_1_ENTITY: sensor.calendar_event_2
  EVENT_2_ENTITY: sensor.calendar_event_3
  EVENT_3_ENTITY: sensor.calendar_event_4

  EVENT_TIME_ATTR: message