substitutions:
  DAY_0_ENTITY: sensor.forecast_day_0
  DAY_1_ENTITY: sensor.forecast_day_1
  DAY_2_ENTITY: sensor.forecast_day_2
  DAY_3_ENTITY: sensor.forecast_day_3
  DAY_4_ENTITY: sensor.forecast_day_4

  DAYS_DATE_ATTR: day
  DAYS_CONDITIONS_ATTR: condition

  DAYS_Y_POSITION_ENTITY: sensor.forecast_day_y_positions
  DAY_0_HIGH_Y_ATTR: day_0_high
  DAY_0_LOW_Y_ATTR: day_0_low
  DAY_1_HIGH_Y_ATTR: day_1_high
  DAY_2_HIGH_Y_ATTR: day_2_high
  DAY_3_HIGH_Y_ATTR: day_3_high
  DAY_4_HIGH_Y_ATTR: day_4_high

  DAYS_LOW_TEMP_ATTR: low
  DAY_1_LOW_Y_ATTR: day_1_low
  DAY_2_LOW_Y_ATTR: day_2_low
  DAY_3_LOW_Y_ATTR: day_3_low
  DAY_4_LOW_Y_ATTR: day_4_low

  F_MIN_TEMP_ATTR: f_min
  F_MAX_TEMP_ATTR: f_max

  Y_MIN_TEMP_ATTR: y_min
  Y_MAX_TEMP_ATTR: y_max