substitutions:
  CURRENT_TEMP_ENTITY: sensor.current_temperature
  CURRENT_CONDITIONS_ENTITY: weather.weather_hourly

  HR_0_ENTITY: sensor.forecast_1
  HR_1_ENTITY: sensor.forecast_2
  HR_2_ENTITY: sensor.forecast_3
  HR_3_ENTITY: sensor.forecast_4

  CONDITIONS_ATTR: condition
  TIME_ATTR: timestamp
