pca6416a:
  - id: pca6416a_hub
    address: 0x20

touchscreen:
  - platform: ektf2232
    interrupt_pin: GPIO36
    rts_pin: 
      pca6416a: pca6416a_hub
      number: 10
    on_touch:
      - logger.log:
          format: "touch x=%d, y=%d"
          args: ['touch.x', 'touch.y']

switch:
  - platform: gpio
    name: Inkplate Touchscreen enabled
    restore_mode: ALWAYS_ON
    pin:
      pca6416a: pca6416a_hub
      number: 12
      inverted: true

i2c:

power_supply:
  - id: backlight_power
    keep_on_time: 0.2s
    enable_time: 0s
    pin:
      pca6416a: pca6416a_hub
      number: 11

output:
  - platform: mcp47a1
    id: backlight_brightness_output
    power_supply: backlight_power

light:
  - platform: monochromatic
    output: backlight_brightness_output
    id: backlight
    default_transition_length: 0.2s
    name: ${DEVICE_NAME} Backlight
    on_turn_on:
      then:
        - script.execute: turn_off_backlight_timeout
    on_turn_off:
      then:
        - script.execute: backlight_turned_off

number:
  - platform: template
    name: ${DEVICE_NAME} Backlight Timeout
    optimistic: true
    min_value: 1
    max_value: 360
    step: 1
    restore_value: true
    id: backlight_timeout