lambda: |-
  std::map<std::string, std::string> weather_icon_map
    {
      {"cloudy", "\U000F0590"},
      {"cloudy-alert", "\U000F0F2F"},
      {"cloudy-arrow-right", "\U000F0E6E"},
      {"fog", "\U000F0591"},
      {"hail", "\U000F0592"},
      {"hazy", "\U000F0F30"},
      {"hurricane", "\U000F0898"},
      {"lightning", "\U000F0593"},
      {"lightning-rainy", "\U000F067E"},
      {"night", "\U000F0594"},
      {"clear-night", "\U000F0594"},
      {"night-partly-cloudy", "\U000F0F31"},
      {"partlycloudy", "\U000F0595"},
      {"partly-lightning", "\U000F0F32"},
      {"partly-rainy", "\U000F0F33"},
      {"partly-snowy", "\U000F0F34"},
      {"partly-snowy-rainy", "\U000F0F35"},
      {"pouring", "\U000F0596"},
      {"rainy", "\U000F0597"},
      {"snowy", "\U000F0598"},
      {"snowy-heavy", "\U000F0F36"},
      {"snowy-rainy", "\U000F067F"},
      {"sunny", "\U000F0599"},
      {"sunny-alert", "\U000F0F37"},
      {"sunny-off", "\U000F14E4"},
      {"sunset", "\U000F059A"},
      {"sunset-down", "\U000F059B"},
      {"sunset-up", "\U000F059C"},
      {"tornado", "\U000F0F38"},
      {"windy", "\U000F059D"},
      {"windy-variant", "\U000F059E"},
      {"calendar","\U000F00ED"},
      {"trash","\U000F01B4"},
      {"recycle","\U000F044C"}
    };
  it.fill(COLOR_ON);
  it.printf(240, 5, id(${G_SANS_BOLD_ID_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(${CURRENT_TIME_ID}).state.c_str());
  it.printf(240, 55, id(${G_SANS_BOLD_ID_LG}), RED, TextAlign::TOP_CENTER, "%s", "WEATHER");

  it.filled_circle(70, id(${DAY_0_HIGH_Y_ID}).state, 10, RED);
  it.filled_circle(70, id(${DAY_0_HIGH_Y_ID}).state + id(${DAY_0_LOW_Y_ID}).state, 10, RED);
  it.filled_rectangle(60, id(${DAY_0_HIGH_Y_ID}).state, 20, id(${DAY_0_LOW_Y_ID}).state, RED);
  it.filled_rectangle(55, id(${DAY_0_HIGH_Y_ID}).state -10, 5, id(${DAY_0_LOW_Y_ID}).state + 20, Color::WHITE);
  it.filled_rectangle(80, id(${DAY_0_HIGH_Y_ID}).state -10, 5, id(${DAY_0_LOW_Y_ID}).state + 20, Color::WHITE);
  it.printf(70, id(${DAY_0_HIGH_Y_ID}).state - 10, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::BOTTOM_CENTER, "%2.0f°F", id(${DAY_0_HIGH_TEMP_ID}).state);
  it.printf(70, id(${DAY_0_HIGH_Y_ID}).state + id(${DAY_0_LOW_Y_ID}).state + 10, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(${DAY_0_LOW_TEMP_ID}).state);
  it.printf(70, id(${DAY_0_HIGH_Y_ID}).state + id(${DAY_0_LOW_Y_ID}).state + 40, id(${G_SANS_REG_ID_SM}), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(${DAY_0_DAY_ID}).state.c_str());
  it.printf(70, id(${DAY_0_HIGH_Y_ID}).state -40, id(${MDI_FONT_ID_SM}), Color::BLACK, TextAlign::BOTTOM_CENTER, "%s", weather_icon_map[id(${DAY_0_CONDITION_ID}).state.c_str()].c_str());

  it.filled_circle(160, id(${DAY_1_HIGH_Y_ID}).state, 10, RED);
  it.filled_circle(160, id(${DAY_1_HIGH_Y_ID}).state + id(${DAY_1_LOW_Y_ID}).state, 10, RED);
  it.filled_rectangle(150, id(${DAY_1_HIGH_Y_ID}).state, 20, id(${DAY_1_LOW_Y_ID}).state, RED);
  it.filled_rectangle(145, id(${DAY_1_HIGH_Y_ID}).state - 10 , 5, id(${DAY_1_LOW_Y_ID}).state + 20, Color::WHITE);
  it.filled_rectangle(170, id(${DAY_1_HIGH_Y_ID}).state - 10 , 5, id(${DAY_1_LOW_Y_ID}).state + 20, Color::WHITE);
  it.printf(160, id(${DAY_1_HIGH_Y_ID}).state - 10, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::BOTTOM_CENTER, "%2.0f°F", id(${DAY_1_HIGH_TEMP_ID}).state);
  it.printf(160, id(${DAY_1_HIGH_Y_ID}).state + id(${DAY_1_LOW_Y_ID}).state + 10, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(${DAY_1_LOW_TEMP_ID}).state);
  it.printf(160, id(${DAY_1_HIGH_Y_ID}).state + id(${DAY_1_LOW_Y_ID}).state + 40, id(${G_SANS_REG_ID_SM}), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(${DAY_1_DAY_ID}).state.c_str());
  it.printf(160, id(${DAY_1_HIGH_Y_ID}).state -40, id(${MDI_FONT_ID_SM}), Color::BLACK, TextAlign::BOTTOM_CENTER, "%s", weather_icon_map[id(${DAY_1_CONDITION_ID}).state.c_str()].c_str());

  it.filled_circle(250, id(${DAY_2_HIGH_Y_ID}).state, 10, RED);
  it.filled_circle(250, id(${DAY_2_HIGH_Y_ID}).state + id(${DAY_2_LOW_Y_ID}).state, 10, RED);
  it.filled_rectangle(240, id(${DAY_2_HIGH_Y_ID}).state, 20, id(${DAY_2_LOW_Y_ID}).state, RED);
  it.filled_rectangle(235, id(${DAY_2_HIGH_Y_ID}).state - 10, 5, id(${DAY_2_LOW_Y_ID}).state + 20, Color::WHITE);
  it.filled_rectangle(260, id(${DAY_2_HIGH_Y_ID}).state - 10, 5, id(${DAY_2_LOW_Y_ID}).state + 20, Color::WHITE);
  it.printf(250, id(${DAY_2_HIGH_Y_ID}).state - 10, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::BOTTOM_CENTER, "%2.0f°F", id(${DAY_2_HIGH_TEMP_ID}).state);
  it.printf(250, id(${DAY_2_HIGH_Y_ID}).state + id(${DAY_2_LOW_Y_ID}).state + 10, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(${DAY_2_LOW_TEMP_ID}).state);
  it.printf(250, id(${DAY_2_HIGH_Y_ID}).state + id(${DAY_2_LOW_Y_ID}).state + 40, id(${G_SANS_REG_ID_SM}), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(${DAY_2_DAY_ID}).state.c_str());
  it.printf(250, id(${DAY_2_HIGH_Y_ID}).state -40, id(${MDI_FONT_ID_SM}), Color::BLACK, TextAlign::BOTTOM_CENTER, "%s", weather_icon_map[id(${DAY_2_CONDITION_ID}).state.c_str()].c_str());

  it.filled_circle(340, id(${DAY_3_HIGH_Y_ID}).state, 10, RED);
  it.filled_circle(340, id(${DAY_3_HIGH_Y_ID}).state + id(${DAY_3_LOW_Y_ID}).state, 10, RED);
  it.filled_rectangle(330, id(${DAY_3_HIGH_Y_ID}).state, 20, id(${DAY_3_LOW_Y_ID}).state, RED);
  it.filled_rectangle(325, id(${DAY_3_HIGH_Y_ID}).state - 10, 5, id(${DAY_3_LOW_Y_ID}).state + 20, Color::WHITE);
  it.filled_rectangle(350, id(${DAY_3_HIGH_Y_ID}).state - 10, 5, id(${DAY_3_LOW_Y_ID}).state + 20, Color::WHITE);
  it.printf(340, id(${DAY_3_HIGH_Y_ID}).state - 10, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::BOTTOM_CENTER, "%2.0f°F", id(${DAY_3_HIGH_TEMP_ID}).state);
  it.printf(340, id(${DAY_3_HIGH_Y_ID}).state + id(${DAY_3_LOW_Y_ID}).state + 10, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(${DAY_3_LOW_TEMP_ID}).state);
  it.printf(340, id(${DAY_3_HIGH_Y_ID}).state + id(${DAY_3_LOW_Y_ID}).state + 40, id(${G_SANS_REG_ID_SM}), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(${DAY_3_DAY_ID}).state.c_str());
  it.printf(340, id(${DAY_3_HIGH_Y_ID}).state -40, id(${MDI_FONT_ID_SM}), Color::BLACK, TextAlign::BOTTOM_CENTER, "%s", weather_icon_map[id(${DAY_3_CONDITION_ID}).state.c_str()].c_str());

  it.filled_circle(430, id(${DAY_4_HIGH_Y_ID}).state, 10, RED);
  it.filled_circle(430, id(${DAY_4_HIGH_Y_ID}).state + id(${DAY_4_LOW_Y_ID}).state, 10, RED);
  it.filled_rectangle(420, id(${DAY_4_HIGH_Y_ID}).state, 20, id(${DAY_4_LOW_Y_ID}).state, RED);
  it.filled_rectangle(415, id(${DAY_4_HIGH_Y_ID}).state - 10, 5, id(${DAY_4_LOW_Y_ID}).state + 20, Color::WHITE);
  it.filled_rectangle(440, id(${DAY_4_HIGH_Y_ID}).state - 10, 5, id(${DAY_4_LOW_Y_ID}).state + 20, Color::WHITE);
  it.printf(430, id(${DAY_4_HIGH_Y_ID}).state - 10, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::BOTTOM_CENTER, "%2.0f°F", id(${DAY_4_HIGH_TEMP_ID}).state);
  it.printf(430, id(${DAY_4_HIGH_Y_ID}).state + id(${DAY_4_LOW_Y_ID}).state + 10, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(${DAY_4_LOW_TEMP_ID}).state);
  it.printf(430, id(${DAY_4_HIGH_Y_ID}).state + id(${DAY_4_LOW_Y_ID}).state + 40, id(${G_SANS_REG_ID_SM}), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(${DAY_4_DAY_ID}).state.c_str());
  it.printf(430, id(${DAY_4_HIGH_Y_ID}).state -40, id(${MDI_FONT_ID_SM}), Color::BLACK, TextAlign::BOTTOM_CENTER, "%s", weather_icon_map[id(${DAY_4_CONDITION_ID}).state.c_str()].c_str());

  it.printf(60, 133, id(${G_SANS_BOLD_ID_MED}), RED, TextAlign::TOP_LEFT, "%s", weather_icon_map[id(${CURRENT_CONDITIONS_ID}).state.c_str()].c_str());
  it.printf(420, 113, id(${G_SANS_BOLD_ID_XL}), RED, TextAlign::TOP_RIGHT, "%2.0f°", id(${CURRENT_TEMP_ID}).state);

  it.printf(65, 242, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(${HR_0_TIME_ID}).state.c_str());
  it.printf(65, 276, id(${MDI_FONT_ID_MED}), RED, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(${HR_0_CONDITION_ID}).state.c_str()].c_str());
  it.printf(65, 314, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(${HR_0_TEMP_ID}).state);

  it.printf(185, 242, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(${HR_1_TIME_ID}).state.c_str());
  it.printf(185, 276, id(${MDI_FONT_ID_MED}), RED, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(${HR_1_CONDITION_ID}).state.c_str()].c_str());
  it.printf(185, 314, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(${HR_1_TEMP_ID}).state);

  it.printf(300, 242, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(${HR_2_TIME_ID}).state.c_str());
  it.printf(300, 276, id(${MDI_FONT_ID_MED}), RED, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(${HR_2_CONDITION_ID}).state.c_str()].c_str());
  it.printf(300, 314, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(${HR_2_TEMP_ID}).state);

  it.printf(420, 242, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(${HR_3_TIME_ID}).state.c_str());
  it.printf(420, 276, id(${MDI_FONT_ID_MED}), RED, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(${HR_3_CONDITION_ID}).state.c_str()].c_str());
  it.printf(420, 314, id(${G_SANS_BOLD_ID_SM_MED}), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(${HR_3_TEMP_ID}).state);      
