lambda: |-
#include <string>

  std::map<std::string, std::string> weather_icon_map
    {
      {"cloudy", "\U000F0590"},
      {"cloudy-alert", "\U000F0F2F"},
      {"cloudy-arrow-right", "\U000F0E6E"},
      {"fog", "\U000F0591"},
      {"hail", "\U000F0592"},
      {"hazy", "\U000F0F30"},
      {"hurricane", "\U000F0898"},
      {"lightning", "\U000F0593"},
      {"lightning-rainy", "\U000F067E"},
      {"night", "\U000F0594"},
      {"clear-night", "\U000F0594"},
      {"night-partly-cloudy", "\U000F0F31"},
      {"partlycloudy", "\U000F0595"},
      {"partly-lightning", "\U000F0F32"},
      {"partly-rainy", "\U000F0F33"},
      {"partly-snowy", "\U000F0F34"},
      {"partly-snowy-rainy", "\U000F0F35"},
      {"pouring", "\U000F0596"},
      {"rainy", "\U000F0597"},
      {"snowy", "\U000F0598"},
      {"snowy-heavy", "\U000F0F36"},
      {"snowy-rainy", "\U000F067F"},
      {"sunny", "\U000F0599"},
      {"exceptional", "\U000F0599"},
      {"sunny-alert", "\U000F0F37"},
      {"sunny-off", "\U000F14E4"},
      {"sunset", "\U000F059A"},
      {"sunset-down", "\U000F059B"},
      {"sunset-up", "\U000F059C"},
      {"tornado", "\U000F0F38"},
      {"windy", "\U000F059D"},
      {"windy-variant", "\U000F059E"},
      {"calendar","\U000F00ED"},
      {"trash","\U000F01B4"},
      {"recycle","\U000F044C"}
    };
  it.fill(COLOR_ON);
  it.printf(240, 5, id(font_google_bold_medium), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(current_time).state.c_str());
  it.printf(240, 55, id(font_google_bold_large), RED, TextAlign::TOP_CENTER, "%s", "WEATHER");

  it.filled_circle(70, id(weather_temperature_y_0).state, 10, RED);
  it.filled_circle(70, id(weather_temperature_y_0).state + id(weather_temperature_y_1).state, 10, RED);
  it.filled_rectangle(60, id(weather_temperature_y_0).state, 20, id(weather_temperature_y_1).state, RED);
  it.filled_rectangle(55, id(weather_temperature_y_0).state -10, 5, id(weather_temperature_y_1).state + 20, Color::WHITE);
  it.filled_rectangle(80, id(weather_temperature_y_0).state -10, 5, id(weather_temperature_y_1).state + 20, Color::WHITE);
  it.printf(70, id(weather_temperature_y_0).state - 10, id(font_google_bold_small_medium), Color::BLACK, TextAlign::BOTTOM_CENTER, "%2.0f°F", id(weather_temperature_high_day_0).state);
  it.printf(70, id(weather_temperature_y_0).state + id(weather_temperature_y_1).state + 10, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_low_day_0).state);
  it.printf(70, id(weather_temperature_y_0).state + id(weather_temperature_y_1).state + 40, id(font_google_regular_small), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(weather_day_0).state.c_str());
  it.printf(70, id(weather_temperature_y_0).state -40, id(font_mdi_small), Color::BLACK, TextAlign::BOTTOM_CENTER, "%s", weather_icon_map[id(condition_day_0).state.c_str()].c_str());

  it.filled_circle(160, id(weather_temperature_y_2).state, 10, RED);
  it.filled_circle(160, id(weather_temperature_y_2).state + id(weather_temperature_y_3).state, 10, RED);
  it.filled_rectangle(150, id(weather_temperature_y_2).state, 20, id(weather_temperature_y_3).state, RED);
  it.filled_rectangle(145, id(weather_temperature_y_2).state - 10 , 5, id(weather_temperature_y_3).state + 20, Color::WHITE);
  it.filled_rectangle(170, id(weather_temperature_y_2).state - 10 , 5, id(weather_temperature_y_3).state + 20, Color::WHITE);
  it.printf(160, id(weather_temperature_y_2).state - 10, id(font_google_bold_small_medium), Color::BLACK, TextAlign::BOTTOM_CENTER, "%2.0f°F", id(weather_temperature_high_day_1).state);
  it.printf(160, id(weather_temperature_y_2).state + id(weather_temperature_y_3).state + 10, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_low_day_1).state);
  it.printf(160, id(weather_temperature_y_2).state + id(weather_temperature_y_3).state + 40, id(font_google_regular_small), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(weather_day_1).state.c_str());
  it.printf(160, id(weather_temperature_y_2).state -40, id(font_mdi_small), Color::BLACK, TextAlign::BOTTOM_CENTER, "%s", weather_icon_map[id(condition_day_1).state.c_str()].c_str());

  it.filled_circle(250, id(weather_temperature_y_4).state, 10, RED);
  it.filled_circle(250, id(weather_temperature_y_4).state + id(weather_temperature_y_5).state, 10, RED);
  it.filled_rectangle(240, id(weather_temperature_y_4).state, 20, id(weather_temperature_y_5).state, RED);
  it.filled_rectangle(235, id(weather_temperature_y_4).state - 10, 5, id(weather_temperature_y_5).state + 20, Color::WHITE);
  it.filled_rectangle(260, id(weather_temperature_y_4).state - 10, 5, id(weather_temperature_y_5).state + 20, Color::WHITE);
  it.printf(250, id(weather_temperature_y_4).state - 10, id(font_google_bold_small_medium), Color::BLACK, TextAlign::BOTTOM_CENTER, "%2.0f°F", id(weather_temperature_high_day_2).state);
  it.printf(250, id(weather_temperature_y_4).state + id(weather_temperature_y_5).state + 10, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_low_day_2).state);
  it.printf(250, id(weather_temperature_y_4).state + id(weather_temperature_y_5).state + 40, id(font_google_regular_small), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(weather_day_2).state.c_str());
  it.printf(250, id(weather_temperature_y_4).state -40, id(font_mdi_small), Color::BLACK, TextAlign::BOTTOM_CENTER, "%s", weather_icon_map[id(condition_day_2).state.c_str()].c_str());

  it.filled_circle(340, id(weather_temperature_y_6).state, 10, RED);
  it.filled_circle(340, id(weather_temperature_y_6).state + id(weather_temperature_y_7).state, 10, RED);
  it.filled_rectangle(330, id(weather_temperature_y_6).state, 20, id(weather_temperature_y_7).state, RED);
  it.filled_rectangle(325, id(weather_temperature_y_6).state - 10, 5, id(weather_temperature_y_7).state + 20, Color::WHITE);
  it.filled_rectangle(350, id(weather_temperature_y_6).state - 10, 5, id(weather_temperature_y_7).state + 20, Color::WHITE);
  it.printf(340, id(weather_temperature_y_6).state - 10, id(font_google_bold_small_medium), Color::BLACK, TextAlign::BOTTOM_CENTER, "%2.0f°F", id(weather_temperature_high_day_3).state);
  it.printf(340, id(weather_temperature_y_6).state + id(weather_temperature_y_7).state + 10, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_low_day_3).state);
  it.printf(340, id(weather_temperature_y_6).state + id(weather_temperature_y_7).state + 40, id(font_google_regular_small), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(weather_day_3).state.c_str());
  it.printf(340, id(weather_temperature_y_6).state -40, id(font_mdi_small), Color::BLACK, TextAlign::BOTTOM_CENTER, "%s", weather_icon_map[id(condition_day_3).state.c_str()].c_str());

  it.filled_circle(430, id(weather_temperature_y_8).state, 10, RED);
  it.filled_circle(430, id(weather_temperature_y_8).state + id(weather_temperature_y_9).state, 10, RED);
  it.filled_rectangle(420, id(weather_temperature_y_8).state, 20, id(weather_temperature_y_9).state, RED);
  it.filled_rectangle(415, id(weather_temperature_y_8).state - 10, 5, id(weather_temperature_y_9).state + 20, Color::WHITE);
  it.filled_rectangle(440, id(weather_temperature_y_8).state - 10, 5, id(weather_temperature_y_9).state + 20, Color::WHITE);
  it.printf(430, id(weather_temperature_y_8).state - 10, id(font_google_bold_small_medium), Color::BLACK, TextAlign::BOTTOM_CENTER, "%2.0f°F", id(weather_temperature_high_day_4).state);
  it.printf(430, id(weather_temperature_y_8).state + id(weather_temperature_y_9).state + 10, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_low_day_4).state);
  it.printf(430, id(weather_temperature_y_8).state + id(weather_temperature_y_9).state + 40, id(font_google_regular_small), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(weather_day_4).state.c_str());
  it.printf(430, id(weather_temperature_y_8).state -40, id(font_mdi_small), Color::BLACK, TextAlign::BOTTOM_CENTER, "%s", weather_icon_map[id(condition_day_4).state.c_str()].c_str());

  it.printf(60, 133, id(font_google_bold_medium), RED, TextAlign::TOP_LEFT, "%s", weather_icon_map[id(weather_condition_now).state.c_str()].c_str());
  it.printf(420, 113, id(font_google_bold_x_large), RED, TextAlign::TOP_RIGHT, "%2.0f°", id(weather_temperature).state);

  it.printf(65, 242, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(weather_timestamp_0).state.c_str());
  it.printf(65, 276, id(font_mdi_medium), RED, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(weather_condition_0).state.c_str()].c_str());
  it.printf(65, 314, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_hr_0).state);

  it.printf(185, 242, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(weather_timestamp_1).state.c_str());
  it.printf(185, 276, id(font_mdi_medium), RED, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(weather_condition_1).state.c_str()].c_str());
  it.printf(185, 314, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_hr_1).state);

  it.printf(300, 242, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(weather_timestamp_2).state.c_str());
  it.printf(300, 276, id(font_mdi_medium), RED, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(weather_condition_2).state.c_str()].c_str());
  it.printf(300, 314, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_hr_2).state);

  it.printf(420, 242, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%s", id(weather_timestamp_3).state.c_str());
  it.printf(420, 276, id(font_mdi_medium), RED, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(weather_condition_3).state.c_str()].c_str());
  it.printf(420, 314, id(font_google_bold_small_medium), Color::BLACK, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_hr_3).state);      
