esp32:
  board: nodemcu-32s
  framework:
    type: arduino
api:
  password: !secret API_KEY

ota:
  password: !secret OTA_PASSWORD

esphome:
  name: ${ESPHOME_NAME}
  on_boot:
    then:
      - script.execute: ${BOOT_SCRIPT_NAME}
      
logger:

captive_portal:

wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASSWORD
  use_address: ${IP_ADDRESS}
  ap:
    ssid: ${AP_SSID}
    password: ${AP_PASSWORD}
  manual_ip:
    gateway: ${GATEWAY_IP}
    subnet: ${SUBNET}
    dns1: ${DNS_1_IP}
    static_ip: ${IP_ADDRESS}
  power_save_mode: none

packages:
  display: !include display/display.yaml
  fonts: !include fonts/fonts.yaml
  images: !include images/images.yaml
  binary_sensors: !include sensors/binary_sensors.yaml
  sensors: !include sensors/sensors.yaml
  text_sensors: !include sensors/text_sensors.yaml

  calendar_subs: !include substitutions/calendar.yaml
  weather_day: !include substitutions/day_weather.yaml
  hour_weather: !include substitutions/hour_weather.yaml
  misc_sensors: !include substitutions/misc_sensors.yaml
  display_config_subs: !include substitutions/display_config.yaml
  display_font_img_subs: !include substitutions/display_fonts_img.yaml
  esphome_subs: !include substitutions/esphome.yaml
  network_subs: !include substitutions/network.yaml

switch:
  - platform: restart
    name: Kitchen Display Restart