binary_sensor:
  - platform: gpio
    pin:
      number: ${BUTTON_1_PIN}
      mode:
        input: true
        pullup: true
    name: ${BUTTON_1_NAME}
    internal: true
    filters:
      - delayed_on: ${BUTTON_DELAY_ON}
      - delayed_off: ${BUTTON_DELAY_OFF}
      - invert
    on_press:
      then: 
        - script.execute:
            id: page_select
            page_id: !lambda return ${BUTTON_1_PAGE};

  - platform: gpio
    pin:
      number: ${BUTTON_2_PIN}
      mode:
        input: true
        pullup: true
    name: ${BUTTON_2_NAME}
    internal: true
    filters:
      - delayed_on: ${BUTTON_DELAY_ON}
      - delayed_off: ${BUTTON_DELAY_OFF}
      - invert
    on_press:
      then:
        - script.execute:
            id: page_select
            page_id: !lambda return ${BUTTON_2_PAGE};
  - platform: gpio
    pin:
      number: ${BUTTON_3_PIN}
      mode:
        input: true
        pullup: true
    name: ${BUTTON_3_NAME}
    internal: true
    filters:
      - delayed_on: ${BUTTON_DELAY_ON}
      - delayed_off: ${BUTTON_DELAY_OFF}
      - invert
    on_press: 
      then: 
        - script.execute:
            id: page_select
            page_id: !lambda return ${BUTTON_3_PAGE};