sensor:
############################################################
####################      WEATHER      #####################
############################################################
  - platform: homeassistant
    entity_id: ${CURRENT_TEMP_ENTITY}
    id: weather_temperature
    
  - platform: homeassistant
    entity_id: ${HR_0_ENTITY}
    id: weather_temperature_hr_0
    
  - platform: homeassistant
    entity_id: ${HR_1_ENTITY}
    id: weather_temperature_hr_1
    
  - platform: homeassistant
    entity_id: ${HR_2_ENTITY}
    id: weather_temperature_hr_2
    
  - platform: homeassistant
    entity_id: ${HR_3_ENTITY}
    id: weather_temperature_hr_3

  - platform: homeassistant
    id: weather_temperature_high_day_0
    entity_id: ${DAY_0_ENTITY}

  - platform: homeassistant
    id: weather_temperature_low_day_0
    entity_id: ${DAY_0_ENTITY}
    attribute: ${DAYS_LOW_TEMP_ATTR}

  - platform: homeassistant
    id: weather_temperature_high_day_1
    entity_id: ${DAY_1_ENTITY}

  - platform: homeassistant
    id: weather_temperature_low_day_1
    entity_id: ${DAY_1_ENTITY}
    attribute: ${DAYS_LOW_TEMP_ATTR}

  - platform: homeassistant
    id: weather_temperature_high_day_2
    entity_id: ${DAY_2_ENTITY}

  - platform: homeassistant
    id: weather_temperature_low_day_2
    entity_id: ${DAY_2_ENTITY}
    attribute: ${DAYS_LOW_TEMP_ATTR}

  - platform: homeassistant
    id: weather_temperature_high_day_3
    entity_id: ${DAY_3_ENTITY}

  - platform: homeassistant
    id: weather_temperature_low_day_3
    entity_id: ${DAY_3_ENTITY}
    attribute: ${DAYS_LOW_TEMP_ATTR}

  - platform: homeassistant
    id: weather_temperature_high_day_4
    entity_id: ${DAY_4_ENTITY}

  - platform: homeassistant
    id: weather_temperature_low_day_4
    entity_id: ${DAY_4_ENTITY}
    attribute: ${DAYS_LOW_TEMP_ATTR}

  - platform: homeassistant
    id: weather_temperature_y_0
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${DAY_0_HIGH_Y_ATTR}

  - platform: homeassistant
    id: weather_temperature_y_1
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${DAY_0_LOW_Y_ATTR}
    
  - platform: homeassistant
    id: weather_temperature_y_2
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${DAY_1_HIGH_Y_ATTR}

  - platform: homeassistant
    id: weather_temperature_y_3
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${DAY_1_LOW_Y_ATTR}
    
  - platform: homeassistant
    id: weather_temperature_y_4
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${DAY_2_HIGH_Y_ATTR}

  - platform: homeassistant
    id: weather_temperature_y_5
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${DAY_2_LOW_Y_ATTR}
    
  - platform: homeassistant
    id: weather_temperature_y_6
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${DAY_3_HIGH_Y_ATTR}

  - platform: homeassistant
    id: weather_temperature_y_7
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${DAY_3_LOW_Y_ATTR}
    
  - platform: homeassistant
    id: weather_temperature_y_8
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${DAY_4_HIGH_Y_ATTR}

  - platform: homeassistant
    id: weather_temperature_y_9
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${DAY_4_LOW_Y_ATTR}

  - platform: homeassistant
    id: ${F_MIN_TEMP_ID}
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${F_MIN_TEMP_ATTR}

  - platform: homeassistant
    id: ${F_MAX_TEMP_ID}
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${F_MAX_TEMP_ATTR}

  - platform: homeassistant
    id: weather_temperature_day_y_min
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${Y_MIN_TEMP_ATTR}

  - platform: homeassistant
    id: weather_temperature_day_y_max
    entity_id: ${DAYS_Y_POSITION_ENTITY}
    attribute: ${Y_MAX_TEMP_ATTR}

    