text_sensor:
############################################################
####################      COMMUTE      #####################
############################################################
  - platform: homeassistant
    entity_id: ${PERSON_1_COMMUTE_ENTITY}
    id: PERSON_1_commute

  - platform: homeassistant
    entity_id: ${PERSON_1_COMMUTE_ENTITY}
    attribute: ${COMMUTE_ROUTE_ATTR}
    id: PERSON_1_route
  
  - platform: homeassistant
    entity_id: ${PERSON_1_COMMUTE_ENTITY}
    attribute: ${COMMUTE_TO_ATTR}
    id: PERSON_1_travel
  
  - platform: homeassistant
    entity_id: ${PERSON_1_COMMUTE_ENTITY}
    attribute: ${LOCATION_ATTR}
    id: PERSON_1_location

  - platform: homeassistant
    entity_id: ${PERSON_2_COMMUTE_ENTITY}
    id: PERSON_2_commute

  - platform: homeassistant
    entity_id: ${PERSON_2_COMMUTE_ENTITY}
    attribute: ${COMMUTE_ROUTE_ATTR}
    id: PERSON_2_route
  
  - platform: homeassistant
    entity_id: ${PERSON_2_COMMUTE_ENTITY}
    attribute: ${COMMUTE_TO_ATTR}
    id: PERSON_2_travel

  - platform: homeassistant
    entity_id: ${PERSON_2_COMMUTE_ENTITY}
    attribute: ${LOCATION_ATTR}
    id: PERSON_2_location

############################################################
####################      WEATHER      #####################
############################################################
  # - platform: homeassistant
  #   entity_id: weather.keye_hourly
  #   id: weather_state

  - platform: homeassistant
    entity_id: ${CURRENT_CONDITIONS_ENTITY}
    id: weather_condition_now
    
  - platform: homeassistant
    entity_id: ${HR_0_ENTITY}
    attribute: ${CONDITIONS_ATTR}
    id: weather_condition_0

  - platform: homeassistant
    entity_id: ${HR_0_ENTITY}
    attribute: ${TIME_ATTR}
    id: weather_timestamp_0
    
  - platform: homeassistant
    entity_id: ${HR_1_ENTITY}
    attribute: ${CONDITIONS_ATTR}
    id: weather_condition_1

  - platform: homeassistant
    entity_id: ${HR_1_ENTITY}
    attribute: ${TIME_ATTR}
    id: weather_timestamp_1
    
  - platform: homeassistant
    entity_id: ${HR_2_ENTITY}
    attribute: ${CONDITIONS_ATTR}
    id: weather_condition_2

  - platform: homeassistant
    entity_id: ${HR_2_ENTITY}
    attribute: ${TIME_ATTR}
    id: weather_timestamp_2
    
  - platform: homeassistant
    entity_id: ${HR_3_ENTITY}
    attribute: ${CONDITIONS_ATTR}
    id: weather_condition_3

  - platform: homeassistant
    entity_id: ${HR_3_ENTITY}
    attribute: ${TIME_ATTR}
    id: weather_timestamp_3

  - platform: homeassistant
    entity_id: ${DAY_0_ENTITY}
    attribute: ${DAYS_DATE_ATTR}
    id: weather_day_0
    
  - platform: homeassistant
    entity_id: ${DAY_1_ENTITY}
    attribute: ${DAYS_DATE_ATTR}
    id: weather_day_1

  - platform: homeassistant
    entity_id: ${DAY_2_ENTITY}
    attribute: ${DAYS_DATE_ATTR}
    id: weather_day_2
    
  - platform: homeassistant
    entity_id: ${DAY_3_ENTITY}
    attribute: ${DAYS_DATE_ATTR}
    id: weather_day_3
    
  - platform: homeassistant
    entity_id: sensor.forecast_day_5
    attribute: ${DAYS_DATE_ATTR}
    id: weather_day_4

  - platform: homeassistant
    entity_id: ${DAY_0_ENTITY}
    attribute: ${DAYS_CONDITIONS_ATTR}
    id: condition_day_0
    
  - platform: homeassistant
    entity_id: ${DAY_1_ENTITY}
    attribute: ${DAYS_CONDITIONS_ATTR}
    id: condition_day_1
    
  - platform: homeassistant
    entity_id: ${DAY_2_ENTITY}
    attribute: ${DAYS_CONDITIONS_ATTR}
    id: condition_day_2
    
  - platform: homeassistant
    entity_id: ${DAY_3_ENTITY}
    attribute: ${DAYS_CONDITIONS_ATTR}
    id: condition_day_3
    
  - platform: homeassistant
    entity_id: ${DAY_4_ENTITY}
    attribute: ${DAYS_CONDITIONS_ATTR}
    id: condition_day_4
    
############################################################
####################      CALENDAR      ####################
############################################################
    
  - platform: homeassistant
    entity_id: ${CURRENT_TIME_ENTITY}
    id: current_time

  - platform: homeassistant
    entity_id: ${EVENT_0_ENTITY}
    id: cal_event_1

  - platform: homeassistant
    entity_id: ${EVENT_0_ENTITY}
    attribute: ${EVENT_TIME_ATTR}
    id: cal_event_1_message

  - platform: homeassistant
    entity_id: ${EVENT_1_ENTITY}
    id: cal_event_2

  - platform: homeassistant
    entity_id: ${EVENT_1_ENTITY}
    attribute: ${EVENT_TIME_ATTR}
    id: cal_event_2_message

  - platform: homeassistant
    entity_id: ${EVENT_2_ENTITY}
    id: cal_event_3

  - platform: homeassistant
    entity_id: ${EVENT_2_ENTITY}
    attribute: ${EVENT_TIME_ATTR}
    id: cal_event_3_message

  - platform: homeassistant
    entity_id: ${EVENT_3_ENTITY}
    id: cal_event_4
    
  - platform: homeassistant
    entity_id: ${EVENT_3_ENTITY}
    attribute: ${EVENT_TIME_ATTR}
    id: cal_event_4_message

############################################################
######################      BABY      ######################
############################################################
  - platform: homeassistant
    entity_id: ${BABY_LAST_FEED_TIME_ENTITY}
    id: last_feed

  - platform: homeassistant
    entity_id: ${BABY_LAST_CHANGE_TIME_ENTITY}
    id: last_change

  - platform: homeassistant
    entity_id: ${BABY_LAST_FEED_TIME_ENTITY}
    attribute: rel_time
    id: last_feed_rel

  - platform: homeassistant
    entity_id: ${BABY_LAST_FEED_TIME_ENTITY}
    attribute: amount
    id: last_feed_amt

  - platform: homeassistant
    entity_id: ${BABY_DAILY_FEED_AMOUNT_ENTITY}
    attribute: amount
    id: daily_feed_amount

  - platform: homeassistant
    entity_id: ${BABY_DAILY_FEED_AMOUNT_ENTITY}
    attribute: count
    id: daily_feed_count

  - platform: homeassistant
    entity_id: ${BABY_LAST_CHANGE_TIME_ENTITY}
    attribute: rel_time
    id: last_change_rel

  - platform: homeassistant
    entity_id: ${BABY_LAST_CHANGE_ENTITY}
    attribute: descriptive
    id: last_change_type

  - platform: homeassistant
    entity_id: ${BABY_DAILY_CHANGE_DETAILS_ENTITY}
    attribute: count
    id: daily_change_count

  - platform: homeassistant
    entity_id: ${BABY_DAILY_CHANGE_DETAILS_ENTITY}
    attribute: types
    id: daily_change_types